Version:
  Algorithm: rec_app
  Versions: 0.2.1

HBase_db:
  ZooKeeperQuorum: "emr-worker-1.cluster-181564,emr-worker-2.cluster-181564,emr-header-1.cluster-181564"
  User: "recommender/user@EMR.181564.COM"

Comic_data:
  Host: 192.168.1.65
  Port: "3306"
  User: root
  Password: "w&cf3ImdzkJVyWwJ"
  Db_name: samh
  Table_name:
    Comic: cartoon
  Max_conns: 10
  Time_out: 50

Redis_items:
  test_item:
    Prefix: "test:"
    Expire: 100
    Len: 10
  test_item2:
    Prefix: "test:"
    Expire: 200
    Len: 5

Redis:
  Addr: "172.16.1.105:7007"
  Password: "0iY87blaERqARYie"
  Pool_size: 200
  Db: 0