Version:
  Algorithm: rec_app
  Versions: 0.2.1

HBase_db:
  ZooKeeperQuorum: "emr-worker-1.cluster-75930,emr-header-1.cluster-75930,emr-header-2.cluster-75930"
  User: "recommender/user@EMR.75930.COM"
  Namespace: "default"
  Table_name:
    Item: item

Comic_data:
  Host: 172.16.1.105
  Port: "3306"
  User: recommender
  Password: "BhRuKc!RJ64eBDQn"
  Db_name: test
  Table_name:
    Comic: behavior
  Max_conns: 10
  Time_out: 50

Redis_items:
  test_item:
    Prefix: "test:"
    Expire: 100
    Len: 10
  test_item2:
    Prefix: "test:"
    Expire: 200
    Len: 5

Redis:
  Addr: "172.16.1.105:7007"
  Password: "0iY87blaERqARYie"
  Pool_size: 200
  Db: 0