Comic_data:
  Host: 47.99.39.114
  Port: "3306"
  User: recommend
  Password: "R1QaL1^G0Fpv8^ZT"
  Db_name: samh
  Table_name:
    Comic: cartoon
  Max_conns: 10
  Time_out: 50



Redis_items:
  Uid_personal_index:
    Prefix: "smh_homepage_personal_index:"
    Expire: 3600
    Len: 10
