Version:
  Algorithm: rec_app
  Versions: 0.2.1

HBase_db:
  ZooKeeperQuorum: "ld-bp17y8n3j6f45p944-proxy-hbaseue.hbaseue.rds.aliyuncs.com:30020"
  User: "root"
  Passwd: "root"
  Namespace: "default"
  Table_name:
    Item: item

HBase_db2:
  Thrift_address: "http://ld-bp17y8n3j6f45p944-proxy-hbaseue.hbaseue.rds.aliyuncs.com:9190"
  User: "root"
  Passwd: "root"
  Namespace: "recommend_samh"
  Table_name:
    Alg: alg_nrt_als

Comic_data:
  Host: 172.16.1.105
  Port: "3306"
  User: recommender
  Password: "BhRuKc!RJ64eBDQn"
  Db_name: test
  Table_name:
    Comic: behavior
  Max_conns: 10
  Time_out: 50

Redis_items:
  test_item:
    Prefix: "testffff:"
    Expire: 1
    Len: 10
  test_item2:
    Prefix: "test:"
    Expire: 200
    Len: 5

Redis:
  Addr: "172.16.1.105:7007"
  Password: "0iY87blaERqARYie"
  Pool_size: 200
  Db: 0

Sentry_dsn: "http://61a9f95ab993403da474cd0dd6850a86@172.16.1.104:9020/2"
